In [23]:
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import pandas as pd
import os
import csv

In [24]:
# Training data 
train_data = pd.read_csv(r"C:\Users\comic\NFL-Predictor\Data\Train-Data\Compiled\testNOPERCENTAGES.csv")
train_data.head()

,T1,T1 Outcome,T1 Score,T1 Location,T1 Avg Points,T1 Avg Yards,T1 NPY/A,T1 NRY/A,T1 3rd,T1 4th,...,T2 NPY/A,T2 NRY/A,T2 3rd,T2 4th,T2 Avg Points Def,T2 Avg Yards Def,T2 NPY/A Def,T2 NRY/A Def,T2 3rd Def,T2 4th Def
0,San Francisco 49ers,1,16,Away,22.9375,356.3125,5.8,4.6,0.52,0.62,...,6.9,3.9,0.39,0.36,17.4375,309.3125,5.4,4.5,0.37,0.38
1,Atlanta Falcons,0,34,Away,25.1250,345.9375,6.1,4.5,0.42,0.60,...,6.0,4.3,0.39,0.54,20.5000,311.5625,5.2,4.8,0.34,0.38
2,Buffalo Bills,0,31,Home,23.6875,349.4375,6.0,4.1,0.43,0.58,...,6.6,4.0,0.40,0.33,21.0000,341.4375,6.0,4.6,0.44,0.56
3,San Diego Chargers,1,34,Away,20.8125,332.8125,5.7,4.6,0.37,0.33,...,5.5,4.1,0.39,0.37,28.5000,329.0625,6.8,4.0,0.42,0.50
4,Miami Dolphins,1,49,Home,23.6250,337.0000,6.0,4.7,0.38,0.30,...,5.0,4.1,0.30,0.40,28.1875,382.3125,6.7,4.0,0.45,0.73

In [25]:
# Testing data with
test_data = pd.read_csv(r"C:\Users\comic\NFL-Predictor\Data\Test-Data\Matchups\Matchup2019.csv")
test_data.head()

,T1,T1 Outcome,T1 Score,T1 Location,T1 Avg Points,T1 Avg Yards,T1 NPY/A,T1 NRY/A,T1 3rd,T1 4th,...,T2 NPY/A,T2 NRY/A,T2 3rd,T2 4th,T2 Avg Points Def,T2 Avg Yards Def,T2 NPY/A Def,T2 NRY/A Def,T2 3rd Def,T2 4th Def
0,Chicago Bears,0,3,Home,17.5000,296.8125,5.3,3.7,0.356,0.333,...,6.1,4.4,0.360,0.500,19.5625,352.6250,6.3,4.7,0.381,0.444
1,Tennessee Titans,1,43,Away,25.1250,362.8125,7.1,5.0,0.378,0.286,...,6.1,4.8,0.362,0.412,24.5625,361.5625,6.3,5.0,0.379,0.353
2,Minnesota Vikings,1,28,Home,25.4375,353.5000,7.1,4.5,0.428,0.533,...,6.4,3.8,0.420,0.619,24.9375,355.8125,6.9,4.2,0.399,0.600
3,Washington Redskins,0,27,Away,16.6250,274.6875,5.3,4.4,0.291,0.429,...,5.9,4.3,0.454,0.333,22.1250,331.6875,6.3,4.1,0.341,0.611
4,Los Angeles Rams,1,30,Away,24.6250,374.8750,6.9,3.7,0.399,0.231,...,5.3,4.7,0.319,0.500,29.3750,374.5000,6.2,5.2,0.399,0.667

In [26]:
features = ["T1 Location", "T2 Location", "T1 Avg Points", "T2 Avg Points", "T1 Avg Yards","T2 Avg Yards", "T1 NPY/A", "T2 NPY/A", "T1 NRY/A", "T2 NRY/A", "T1 Avg Points Def", "T2 Avg Points Def", "T1 Avg Yards Def", "T2 Avg Yards Def", "T1 NPY/A Def", "T2 NPY/A Def","T1 NRY/A Def", "T2 NRY/A Def", "T1 4th Def", "T2 4th Def", "T1 3rd", "T2 3rd", "T1 4th", "T2 4th", "T1 3rd Def", "T2 3rd Def"]
# Here's the features I used

X = train_data[features].copy()
y = train_data['T1 Outcome']

cat_cols = X.select_dtypes(include=["object", "category"]).columns
cat_idx = np.where(X.columns.isin(cat_cols))[0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

train_pool = Pool(X_train, y_train, cat_features=cat_idx)
test_pool  = Pool(X_test,  y_test,  cat_features=cat_idx)

In [27]:
model = CatBoostClassifier(verbose=200)
model.fit(train_pool, eval_set=test_pool)

Learning rate set to 0.043123
0:	learn: 0.6842209	test: 0.6848921	best: 0.6848921 (0)	total: 7.2ms	remaining: 7.19s
200:	learn: 0.4561541	test: 0.5611946	best: 0.5568599 (94)	total: 1.11s	remaining: 4.42s
400:	learn: 0.3569296	test: 0.5799515	best: 0.5568599 (94)	total: 2.25s	remaining: 3.36s
600:	learn: 0.2855377	test: 0.6019774	best: 0.5568599 (94)	total: 3.35s	remaining: 2.22s
800:	learn: 0.2304398	test: 0.6187134	best: 0.5568599 (94)	total: 4.53s	remaining: 1.12s
999:	learn: 0.1888790	test: 0.6363406	best: 0.5568599 (94)	total: 5.82s	remaining: 0us

bestTest = 0.5568598951
bestIteration = 94

Shrink model to first 95 iterations.

In [28]:
# Evaluate and predict
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print(f"Test accuracy: {acc*100:.2f}%")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test accuracy: 72.79%
[[314 116]
 [121 320]]
              precision    recall  f1-score   support

           0       0.72      0.73      0.73       430
           1       0.73      0.73      0.73       441

    accuracy                           0.73       871
   macro avg       0.73      0.73      0.73       871
weighted avg       0.73      0.73      0.73       871