In [1]:
#Final Model created using Random Forest Classifier

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import os

In [5]:
import csv

In [6]:
#Training data with seasons 2002 - 2018 every game
train_data = pd.read_csv(r"C:\Users\comic\NFL-Predictor\Data\Train-Data\Compiled\testNOPERCENTAGES.csv")
train_data.head()
#Here is preview of first 5 games 
#Note if outcome is 1 that means team won the game

,T1,T1 Outcome,T1 Score,T1 Location,T1 Avg Points,T1 Avg Yards,T1 NPY/A,T1 NRY/A,T1 3rd,T1 4th,...,T2 NPY/A,T2 NRY/A,T2 3rd,T2 4th,T2 Avg Points Def,T2 Avg Yards Def,T2 NPY/A Def,T2 NRY/A Def,T2 3rd Def,T2 4th Def
0,San Francisco 49ers,1,16,Away,22.9375,356.3125,5.8,4.6,0.52,0.62,...,6.9,3.9,0.39,0.36,17.4375,309.3125,5.4,4.5,0.37,0.38
1,Atlanta Falcons,0,34,Away,25.1250,345.9375,6.1,4.5,0.42,0.60,...,6.0,4.3,0.39,0.54,20.5000,311.5625,5.2,4.8,0.34,0.38
2,Buffalo Bills,0,31,Home,23.6875,349.4375,6.0,4.1,0.43,0.58,...,6.6,4.0,0.40,0.33,21.0000,341.4375,6.0,4.6,0.44,0.56
3,San Diego Chargers,1,34,Away,20.8125,332.8125,5.7,4.6,0.37,0.33,...,5.5,4.1,0.39,0.37,28.5000,329.0625,6.8,4.0,0.42,0.50
4,Miami Dolphins,1,49,Home,23.6250,337.0000,6.0,4.7,0.38,0.30,...,5.0,4.1,0.30,0.40,28.1875,382.3125,6.7,4.0,0.45,0.73

In [7]:
#Testing data with 2019 season
test_data = pd.read_csv(r"C:\Users\comic\NFL-Predictor\Data\Test-Data\Matchups\Matchup2019.csv")
test_data.head()
#Here is a preview of first 5 games 
#Note if outcome is 1 that means team won the game

,T1,T1 Outcome,T1 Score,T1 Location,T1 Avg Points,T1 Avg Yards,T1 NPY/A,T1 NRY/A,T1 3rd,T1 4th,...,T2 NPY/A,T2 NRY/A,T2 3rd,T2 4th,T2 Avg Points Def,T2 Avg Yards Def,T2 NPY/A Def,T2 NRY/A Def,T2 3rd Def,T2 4th Def
0,Chicago Bears,0,3,Home,17.5000,296.8125,5.3,3.7,0.356,0.333,...,6.1,4.4,0.360,0.500,19.5625,352.6250,6.3,4.7,0.381,0.444
1,Tennessee Titans,1,43,Away,25.1250,362.8125,7.1,5.0,0.378,0.286,...,6.1,4.8,0.362,0.412,24.5625,361.5625,6.3,5.0,0.379,0.353
2,Minnesota Vikings,1,28,Home,25.4375,353.5000,7.1,4.5,0.428,0.533,...,6.4,3.8,0.420,0.619,24.9375,355.8125,6.9,4.2,0.399,0.600
3,Washington Redskins,0,27,Away,16.6250,274.6875,5.3,4.4,0.291,0.429,...,5.9,4.3,0.454,0.333,22.1250,331.6875,6.3,4.1,0.341,0.611
4,Los Angeles Rams,1,30,Away,24.6250,374.8750,6.9,3.7,0.399,0.231,...,5.3,4.7,0.319,0.500,29.3750,374.5000,6.2,5.2,0.399,0.667

In [8]:
from sklearn.ensemble import RandomForestClassifier


y = train_data["T1 Outcome"]#Want to train data on the first team's outcome column 


features = ["T1 Location", "T2 Location", "T1 Avg Points", "T2 Avg Points", "T1 Avg Yards","T2 Avg Yards", "T1 NPY/A", "T2 NPY/A", "T1 NRY/A", "T2 NRY/A", "T1 Avg Points Def", "T2 Avg Points Def", "T1 Avg Yards Def", "T2 Avg Yards Def", "T1 NPY/A Def", "T2 NPY/A Def","T1 NRY/A Def", "T2 NRY/A Def", "T1 4th Def", "T2 4th Def", "T1 3rd", "T2 3rd", "T1 4th", "T2 4th", "T1 3rd Def", "T2 3rd Def"]
#Here's the features I used to first achieve over 70% prediction accuracy 

x = pd.get_dummies(train_data[features])
x_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=1, min_samples_leaf=25,n_jobs=5, oob_score=True)#Subject to change these parameters, but these seem to work pretty well
model.fit(x, y)
predictions = model.predict(x_test)

output = pd.DataFrame({'T1': test_data.T1, 'T1 Outcome': predictions})
output.to_csv('FinalModel.csv', index=False)#Put model into a .csv file

In [9]:
prediction_model = pd.read_csv(r"C:\Users\comic\FinalModel.csv")
prediction_model.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\comic\\FinalModel.csv'

In [ ]:
output = pd.DataFrame({'Team': prediction_model['T1'], 'Outcomes': predictions})
print(output)

In [11]:
import random

In [12]:
right = 0
wrong = 0

In [13]:
for i in range(len(prediction_model["T1"])):
    if test_data["T1 Outcome"][i] == prediction_model['T1 Outcome'][i]:
        right+=1
    else:
        wrong+=1

In [14]:
print(str((right/(right+wrong))*100)+"%")

71.484375%

In [ ]:
#Here's the percentage I get from the 2019 season, almost 71.5% accurate!